name: Manual Production Release

on:
  workflow_dispatch:
    # inputs:
    #   release_version:
    #     description: 'Release version'
    #     required: true

permissions:
  contents: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Release
        run: |
          echo "Installing semantic-release..."
          python3 -m pip install -q --upgrade pip
          pip install -q python-semantic-release
          echo "Checking out the branch MAIN..."
          git fetch --tags
          git fetch --all
          git log -n 5 --decorate
          echo "Releasing a new version..."
          set -x
          semantic-release --config package.json -vv version --no-vcs-release --skip-build
          TAG_TO_RELEAE=$(semantic-release --config package.json  version --print-tag)
          echo "TAG_TO_RELEAE=${TAG_TO_RELEAE}"
          git log -n 5 --decorate
          semantic-release --config package.json -vv changelog --post-to-release-tag ${TAG_TO_RELEAE}
          set +x
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        #echo "Creating release version ${{ github.event.inputs.release_version }}"
          # Add release creation steps here